[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "e94f78ac2bbb2bb20ca37236b614885ec03785bf"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "2f2fe2991efbd4956754707090ab99a55ddcf329a7fee651b64cd719114a8988"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "f495f3992e1fbe27abccceb978990ec10ec154b1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "b60b5630c9cddaf0ee3591f7bb088183f89cdb695e848b138d65a5409014a621"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "4debe49512057e946a21b7a1dbbb6c8e5ecac135"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "8a7cf9bdca8167659a0b385443291eabf29cac0377ffb8bc75ee5bbbf1d7da1d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "11822308f848efafad741b0242ff8445398856e7"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "ef2c2e484c53e477634d9a7c2a93e32e94c379b6f66d9d04a27f2ae357d98c33"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "239efc62f34f2107874fc3bed0068733d5191c75"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "a306aeb4aa66079b9180d17a1664580fed39f5d68d4af4b832d6ad47818c3da5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "dbf2792c710de82713d9ff1fea46d24ec811e15b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "b3e2565260213c3ee88e509ef584d5a621a57df75c287dc5ee043e6da533a745"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "310bd36d156dc3d242e719edd4c39b09b3d267ff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "7fd4228f24a31df6d400253f46699587b18b022dbe0c4a93312fac25dcc72828"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "686b166c74b0fdc7bca5b6386e9227c722933093"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "6434bea90d99228e9bc1b5199fb6109825d7f13d1afd05ca990af0c3c720eb39"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "56b95fdff0fcd1c059d414943c269f50b2ad6b3b"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "f42b8288a73d59f6fc57ebb69337c3cf392db956a54d4a2eea241600b0f45103"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.30+0/OpenBLASConsistentFPCSR.v0.3.30.x86_64-w64-mingw32-libgfortran5.tar.gz"
