[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "e4b0c40ccfbafe4214edd9d6b498b1082af34a35"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "9318cb01b3027cfa155dd58ba8b0752bf2888364d79ab474cb493c5b9220ec3e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "07f7d4948d7b21065244cb710c4a80b3c231d657"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "3e2cd1429a808b5e656223a2a65c6915df33321eb342b3b00ea3c9d306228af2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "33758078ac4068f496245a208d81b72c51ef9fca"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "4adec47dd29080b58c5684fd3a1ae797e59a307088ef57d607ed8e4e30ae1bb4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "06228236c54262c8ef8a6192361020c7ba82bb3c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "a79c7de43cd3b129f2f3ea5b9f285b20e4ee83f835ef4669c0f3b01ad26c4e67"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "7d1101be8078bf8ca50b16e0a6408e5f8c2fd761"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "d4e3e700660a8e655796092bd7490872ae50f37d43e5cb2f3bcdbd8f6894eb3f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "ec1ec32f644ea6df4c3eb0bd178d91e72a1908bf"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "57dd540f20b8e6d38f2b026f581fff3c08bf59c61dae959720d664d1d9a57578"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "be1b530f135332b4ec85eca6a50707f5809c5388"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "6d3614a2f17b2fb6e330733fcb5fa5c8c39f7be7e8f20a76b4325cdab775bb6b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "f745620d03f7050aa640dc9a3467066650ddea64"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "853e4da17eb6afc4815f1f8b9a01c6f9f1e1224e22613f4d21148f0669920378"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "3cc40e0ae83e571be5d87c4e02792089e4c34eae"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "8b599b8bce710dad03bff70d3f995ef5367697caecbe1f4fe5240f28b4fcbd7a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.33+0/OpenBLASConsistentFPCSR.v0.3.33.x86_64-w64-mingw32-libgfortran5.tar.gz"
