[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "936c694ff23bd77cd40a0a8e8dadb8f2ec02b48b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "73ef8918084afe2195db821e88495204f6d81c40d0bfae058ec34e21633b5a6f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "d05d1dc943e753f13e68521c483aacd55131f6e0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "b6a4ed461675fe139728c8e897e1e0c4b52729f64355e9c1d845c016e1ec082e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "273e0704afe7c11fd28afa286909091690c3d50e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "1683a2516f42cdbd5115b9b1eef8c3f43cf6db1e2d995dc95a21062495dce0f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "1e3edd2c13255cd0e738a6f18a004d2c99d7498c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "660975e049ccf6c11ae45119b38daad70fe58a29d4b7ccce1f27d702ec5c7bda"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "36bce3696b1573529f5fdbf9b45ec9ce74f6a5c7"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "7a2d59df5ed1e71d7f5f730a044ad9bfbb5e31728e3adf4d9801e30ee99c3b4e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "52aa4ac65f9251ae65b8ef11dce1d1fa736aa9e4"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "5160601aca88617a1819edc193cee21569ab5fdd0535c0fe2b68746775122652"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "7f35b34c8706eb85aa3298d6b38b827b18290a8c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "05612c71d43976c9a735bb632e7ad348d68e3715c1506fb98f1ebd160cf63c6f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "aarch64"
git-tree-sha1 = "4a8cd7cd23ea8ba7ecf8febec8e9c73decf8e45b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "5e026d6c53676c4613a31b6b765dd29645db0395b1d1b6fd107650cfd208dcd7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLASConsistentFPCSR]]
arch = "x86_64"
git-tree-sha1 = "8d164121ab100d45dbe29d7f04870b06c1d8fde1"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASConsistentFPCSR.download]]
    sha256 = "e4896e64b4569e112ba3c0fdbed3682739bfe9ab6f9252521c2cd33c6c664436"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASConsistentFPCSR_jll.jl/releases/download/OpenBLASConsistentFPCSR-v0.3.32+0/OpenBLASConsistentFPCSR.v0.3.32.x86_64-w64-mingw32-libgfortran5.tar.gz"
